services:
  warrden:
    image: ghcr.io/neurekadev/warrden:5
    container_name: warrden
    env_file:
      - .env
    networks:
      - warrden
    volumes:
      - data:/app/data
      - ./config.yaml:/app/data/config.yaml
    restart: unless-stopped

networks:
  warrden:
    name: warrden

volumes:
  data:
